### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by Nagarajukasarla** [harshadgavali/gnome-gesture-improvements#219]
I recently shifted from windows to Linux. In search of touch pad gestures I came across to this repository and decided to install.

OS Details:
```

PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.4"
VERSION="2024.4"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

**What I did :**
First, I have tired to install it directly from gnome extension using [browser extension](https://extensions.gnome.org/extension/4245/gesture-improvements/).

Error:
The settings of extension gestureImprovements@gestures had an error:
```
SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:4:1

Stack trace:
  @file:///home/nag/.local/share/gnome-shell/extensions/gestureImprovements@gestures/prefs.js:3:12
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
```

**Due to above error I have uninstalled it from extensions and followed steps from README.md**
```
git clone https://github.com/harshadgavali/gnome-gesture-improvements.git/
cd gnome-gesture-improvements
npm install
npm run update
```

**Detailed output with error:**
```
> gnome-gestures@1.0.0 update
> npm run pack && make update


> gnome-gestures@1.0.0 pack
> npm run build && make pack


> gnome-gestures@1.0.0 build
> npm run clean && npm run transpile && node --unhandled-rejections=strict build/scripts/transpile.js && npm run lint:package


> gnome-gestures@1.0.0 clean
> rm -rf build && mkdir build


> gnome-gestures@1.0.0 transpile
> npm run lint:extension && tsc


> gnome-gestures@1.0.0 lint:extension
> eslint extension scripts tests

Error: ESLint configuration in .eslintrc.json is invalid:
	- Unexpected top-level property "$schema".

    at validateConfigSchema (/usr/share/nodejs/eslint/lib/shared/config-validator.js:286:15)
    at ConfigArrayFactory._normalizeConfigData (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:469:9)
    at ConfigArrayFactory._loadConfigDataInDirectory (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:445:33)
    at ConfigArrayFactory.loadInDirectory (/usr/share/nodejs/eslint/lib/cli-engine/config-array-factory.js:401:18)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/share/nodejs/eslint/lib/cli-engine/cascading-config-array-factory.js:304:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/share/nodejs/eslint/lib/cli-engine/cascading-config-array-factory.js:323:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/usr/share/nodejs/eslint/lib/cli-engine/cascading-config-array-factory.js:323:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/usr/share/nodejs/eslint/lib/cli-engine/cascading-config-array-factory.js:249:18)
    at FileEnumerator._iterateFilesRecursive (/usr/share/nodejs/eslint/lib/cli-engine/file-enumerator.js:399:49)
    at _iterateFilesRecursive.next (<anonymous>)
```
 
 Please let me know  if I have missed something.

**Comment by HieuTNg** [comment]
I think the error is because your version of Kali is using GNOME 47 which this extension is no longer compatible. It seems like this project is no longer maintained and the last supported version of GNOME is 44. There are some breaking change in GNOME 45. Some people has made some pull request to update the extension but has not been merged since the author is not active. I have taken the initiative to forked the project and update the code base so that it works with GNOME 47 and tested on my machine to ensure all features are working. You can test it at https://github.com/HieuTNg/touchpad-gesture-customization
